<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>HTML2PDF.JS</title>
	<script src="../../js/html2pdf.bundle.js"></script>
	<script src="../../js/prueba.js"></script>
</head>
<body>
	<div id="invocar">
		<h3 style="text-align: center;">CLINICA OFTALMOLOGICA CASTILLO INCIARTE</h3>
		<h3 style="text-align: center;">Y ASOCIADOS C.A.</h3>
		<h3 style="text-align: center;">RIF: J-30403474-1</h3>

		<h3 style="text-align: center;">NORMAS PARA PACIENTES DE CIRUGIA DE RETINA</h3>

		<p>* SI TOMA ASPIRINA O ANTICOAGULANTE, PREVIA AUTORIZACION DE SU MEDICO TRATANTE, SUSPENDER 15 DIAS ANTES DE LA CIRUGIA.</p>

		<p>'* DEBE REALIZAR LOS EXAMENES  PREOPERATORIOS COMPLETOS, (LABORATORIO, RX DE TORAX Y CARDIOVASCULAR), DE FALTAR ALGUNO NO SE PODRAN REVISAR, NI PLANIFICAR LA CIRUGIA.</p>

		<p>* LOS EXAMENES DEBEN SER REVISADOS POR EL MEDICO LOS DIAS LUNES MARTES O JUEVES (LAS CIRUGIAS SERAN SOLO LOS DIAS MIERCOLES.</p>

		<p>* AL SABER LA FECHA  DE  LA  CIRUGIA  EL  PACIENTE  DEBE  ACUDIR A LA ADMINISTRACION DE LA CLINICA EL DIA ANTERIOR PARA LA TRAMITACION  DEL'PAGO RESPECTIVO, DE LO CONTRARIO SERA OMITIDO EL CASO.</p>

		<p>* CUENTAS CORRIENTES A NOMBRE DE LA  CLINICA  OFTALMOLOGICA  CASTILLO INCIARTE Y ASOCIADOS, C.A.'</p>

		<p>PROVINCIAL:  01080361640100014630                    MERCANTIL: 01050093191093041889</p>
		<p>SOFITASA…..: 01370020670000130321                    TESORO…….:01630304603043005474</p>

		<p>ZELLE BOFA:  oeci50@gmail.com  A NOMBRE DE OSCAR CASTILLO INCIARTE'</p>
		<p>BANCOLOMBIA: AHORROS 726-000006-05 A NOMBRE DE: OSCAR E CASTILLO CARVAJAL C.C. 1.127.341.373.</p>

		<p>* DEBE LLAMA EL DIA MARTES A LAS  2:30 PM PARA  INDICARLES  LA  HORA DE LA CIRUGIA.</p>

		<p>* SI TOMA MEDICAMENTOS  PARA LA HIPERTENSION ARTERIAL Y GLICEMIA  NO DEBE SUSPENDERLOS DEBE TOMARLOS A SU HORA CON POCA AGUA.</p>

		<p>* NO COMER NI TOMAR  NINGUN  LIQUIDO SEIS HORAS ANTES DE LA CIRUGIA.</p>

		<p>* TODOS LOS PACIENTES TIENEN CITA EL DIA SIGUIENTE, LOS DE DOMICILIO LEJANO DEBEN HOSPEDARSE EN LA CIUDAD.</p>

		<p>* A LAS DAMAS SE   RECOMIENDA  NO  UTILIZAR  MAQUILLAJE,  NI ESMALTE PARA UÑAS Y NO TRAER JOYAS.</p>

		<p>* BAÑARSE BIEN EL DIA DE  LA CIRUGIA ESPECIALMENTE EL CABELLO Y CARA- ES INDISPENSABLE TRAER LOS  EXAMENES  PRE  OPERATORIOS EL DIA DE  LA CIRUGIA.</p>

		<p>* SE RECOMIENDA VENIR CON UN SOLO  ACOMPA･ANTE  CUMPLIENDO CON   LAS NORMAS DE BIOSEGURIDAD. NO QUITARSE LA MASCARILLA EN NINGUN MOMENTO.</p>

		<p>'* LA CIRUGIA INCLUYE 1 CONTROL POST OPERATORIO SIN COSTO LOS CONTROLES SUCESIVOS SERAN PAGOS.'</p>


		<h5>Av.19 de Abril Edificio Cl｡nica de Ojos P.B. Sector La Bermeja   SAN CRISTOBAL EDO TACHIRA TF:0276-3560133-3560139'</h5>
		<h5>FAX-3558633  e-mail: clicastillo@yahoo.com'</h5>

		<!--<button onclick="">Generar PDF</button>-->
	</div>
	<script type="text/javascript">
		generatePDF();
	</script>
</body>
</html>